### ISSUE TITLE
5.00_01 does not build on FreeBSD out of the box

### ISSUE THREAD

**Issue by eserte** [petdance/html-tidy#29]
On a freebsd 10 system with package tidy-html5 installed:
```
$ perl5.18.4 Makefile.PL 
...
LD_RUN_PATH="/usr/local/lib" cc  -shared  -L/usr/local/lib -fstack-protector  Tidy.o  -o blib/arch/auto/HTML/Tidy/Tidy.so    -ltidy    
/usr/bin/ld: cannot find -ltidy
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```
Problem: the library is installed as -ltidy5: /usr/local/lib/libtidy5.so
Makefile.PL should detect this automatically.

(If this is fixed then compilation is successful, but there are a number of test failures)

Another note: what about naming the new module version HTML::Tidy5, or HTML5::Tidy, so the old HTML::Tidy may still be installed? In some package repositories the new tidy-html5 seems to be missing (e.g. Ubuntu 16.04, CentOS6), so being able to build a tidy module without using CPAN tricks or adding backports repositories would be good.

**Comment by petdance** [comment]
> Another note: what about naming the new module version HTML::Tidy5, or HTML5::Tidy,

I thought about that, but I'm not sure it's very likely that anybody will want to be able to use them both at the same time.

**Comment by petdance** [comment]
> being able to build a tidy module without using CPAN tricks or adding backports repositories would be good.

Oh, I see what you're saying, because CPAN clients aren't made to be able to say "Install HTML::Tidy version 1.60".

**Comment by petdance** [comment]
> Another note: what about naming the new module version HTML::Tidy5, or HTML5::Tidy

This is discussed in #30.

**Comment by petdance** [comment]
> Makefile.PL should detect this automatically.

Do you know what to do to make that happen?

**Comment by eserte** [comment]
A simple fix would be to write something like
```
my $libs = $^O eq 'freebsd' ? '-ltidy5' : '-ltidy';
```
Maybe other *BSD systems need the same change.

A better fix would probably be the use of `Devel::CheckLib` or so.

**Comment by petdance** [comment]
> my $libs = $^O eq 'freebsd' ? '-ltidy5' : '-ltidy';

**Comment by petdance** [comment]
> my $libs = $^O eq 'freebsd' ? '-ltidy5' : '-ltidy';

Oh, sure.  I thought you meant that there was some magic in MakeMaker that would know which to choose of a list of options.

Do you know why it got installed as tidy5 instead of tidy?

**Comment by petdance** [comment]
This has been fixed in bd13a7a in https://github.com/petdance/html-tidy5.

Future changes should go to that new project.

**Comment by eserte** [comment]
Confirmed, now build works (but there are some test failures, see the other ticket).

I think this way it's possible to install old and new library together.

**Comment by petdance** [comment]
The deciding factor for me was when I realized I was going to have to both the old and new Tidy running side-by-side at work until we finished transitiioning.
