### ISSUE TITLE
Should HTML::Tidy become HTML::Tidy5?

### ISSUE THREAD

**Issue by petdance** [petdance/html-tidy#30]
@eserte asks in #29: what about naming the new module version HTML::Tidy5, or HTML5::Tidy, so the old HTML::Tidy may still be installed? In some package repositories the new tidy-html5 seems to be missing (e.g. Ubuntu 16.04, CentOS6), so being able to build a tidy module without using CPAN tricks or adding backports repositories would be good.

**Comment by petdance** [comment]
I thought about this and my biggest thought is that I'm not sure it's very likely that anybody will want to be able to use them both at the same time.

I think @eserte's point is that renaming it would let people using the old HTML::Tidy for HTML4 would still be able to do so easily, without a subsequent 5.x release messing things up.

Thoughts from users and potential users?

**Comment by ghenry** [comment]
HTML5::Tidy would be the best bet IMHO. Tidy5 doesn't make sense :)

**Comment by petdance** [comment]
It doesn't feel right to go into HTML5 top-level space.  I don't think people searching for "HTML" on a cpan search site will get HTML5.

Maybe I should do HTML::Tidy::HTML5.

**Comment by nanis** [comment]
@petdance It's a trade-off between expressiveness and brevity. While technically correct, `HTML::Tidy::HTML5` is too hefty (and makes me ask "where is `HTML::Tidy::HTML4` etc?"). I think `HTML::Tidy5` strikes the right balance.

**Comment by petdance** [comment]
What about the question of "Is it necessary to make it a new module"?  Why not simply keep it as HTML::Tidy?

**Comment by petdance** [comment]
What about the question of if it even needs to be renamed at all?  Why not just keep it HTML::Tidy?

If I make it HTML::Tidy5, then someone could continue to maintain HTML::Tidy.  OTOH, I can't imagine that anyone wants to do that, including me.

**Comment by petdance** [comment]
The new project going forward is https://github.com/petdance/html-tidy5.
